# Default values for ea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: "ea"

image:
  repository: 853771734544.dkr.ecr.us-east-1.amazonaws.com/translator-explanatory-agent:DOCKER_VERSION_VALUE
  imagePullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Name=transltr-eks-ci-blue-ea,Environment=CI
    alb.ingress.kubernetes.io/security-groups: translator-ci-alb-http-sg
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthcheck-path: '/health'  
  host: explanatory-agent.ci.transltr.io

affinity:
   # this ensures only ONE pod will run on each node
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - ea
      topologyKey: "kubernetes.io/hostname"
  # this ensures pod only runs on node with label application=ea
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: application
          operator: In
          values:
          - ea
tolerations:
  - key: "transltr"
    value: "ea"
    operator: "Equal"
    effect: "NoSchedule"
      
restartPolicy: Always

env:
  - name: DB_HOST
    value: transltr-ci-rds-ea-chp-postgresql.ceyknq0yekb3.us-east-1.rds.amazonaws.com
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: postgres-config
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: postgres-config
        key: password
  - name: DB_SCHEMA
    valueFrom:
      secretKeyRef:
        name: postgres-config
        key: schema
  
# envFrom:
#   - secretRef:
#       name: postgres-secret
