apiVersion: v1
kind: Service
metadata:
  name: ea
  namespace: transltr
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ea
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: psql-rds
spec:
  externalName: transltr-ci-rds-ea-chp-postgresql.ceyknq0yekb3.us-east-1.rds.amazonaws.com
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  sessionAffinity: None
  type: ExternalName


