apiVersion: v1
kind: Service
metadata:
  name: explanatoryagent
  namespace: trnsltr
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: explanatoryagent
  type: NodePort
