apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ea.fullname" . }}
  labels:
    {{- include "ea.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ea.selectorLabels" . | nindent 8 }}
        {{- toYaml .Values.ncats.labels | nindent 8 }}
    spec:
      containers:
        - name: easerver
          image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_USERNAME
              value: {{ .Values.db.username }}   
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}     
            - name: DB_NAME
              value: {{ .Values.db.dbname }}
            - name: XARA_APP_DB_HOST
              value: {{ .Values.app_db.host }}
            - name: XARA_APP_DB_USERNAME
              value: {{ .Values.app_db.username }}   
            - name: XARA_APP_DB_PASSWORD
              value: {{ .Values.app_db.password }}     
            - name: XARA_APP_DB_NAME
              value: {{ .Values.app_db.dbname }}
            - name: EXTERNAL_API_HOST
              value: {{ .Values.api_host }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}

